### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by jingostudios** [LaravelDaily/Laravel-Job-Listings-QuickAdminPanel#1]
Is it possible to fix the image issue? You also mentioned it in your video. Thanks.
Please pull, install and see if image works. mine did not. Maybe I missed something!

**Comment by PovilasKorop** [comment]
@jingostudios it's not about the fix in the code, it's about running `php artisan storage:link` command. Read more: https://laravel.com/docs/master/filesystem#the-public-disk

**Comment by jingostudios** [comment]
Thanks! I had tried that, but it did not work for me. After searching from the spatie issues, when running on local, I just update the .env file to take the APP_URL as a string as it was missing the **:8000**
`APP_URL="http://localhost:8000"`
I will check when I run a test on Heroku!
I believe on remote hosting it will not need the :8000 so it should work! Thanks!
