### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by Anoob007** [LaravelDaily/Laravel-Job-Listings-QuickAdminPanel#2]
Not Found
The requested resource /login was not found on this server.
![Screenshot (38)](https://user-images.githubusercontent.com/54050679/76697264-170f0800-66bb-11ea-9f6f-b6066a2063d9.png)

**Comment by PovilasKorop** [comment]
@Anoob007 it's something with your server configuration.

- What is your `APP_URL` in `.env` file? It should be `http://127.0.0.1:8000`
- Have your configured RewriteRule in your web-server?

Cause now your server is looking for `/login` as a folder on the server, not as web address or Laravel route.

**Comment by Anoob007** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/54050679/76697477-baf9b300-66bd-11ea-9a93-5c4693f978dc.png)

**Comment by PovilasKorop** [comment]
Yes so why do you have localhost?

Sorry this issue is not about our repository, it's about your local setup of Laravel. Please read official documentation of server setup and Laravel installation and configuration, closing this issue.
